/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  BlogPost as PrismaBlogPost,
  Comment as PrismaComment,
  Author as PrismaAuthor,
} from "@prisma/client";

import { PublishBlogPostInput } from "../PublishBlogPostInput";

export class BlogPostServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.BlogPostCountArgs, "select">): Promise<number> {
    return this.prisma.blogPost.count(args);
  }

  async blogPosts(
    args: Prisma.BlogPostFindManyArgs
  ): Promise<PrismaBlogPost[]> {
    return this.prisma.blogPost.findMany(args);
  }
  async blogPost(
    args: Prisma.BlogPostFindUniqueArgs
  ): Promise<PrismaBlogPost | null> {
    return this.prisma.blogPost.findUnique(args);
  }
  async createBlogPost(
    args: Prisma.BlogPostCreateArgs
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.create(args);
  }
  async updateBlogPost(
    args: Prisma.BlogPostUpdateArgs
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.update(args);
  }
  async deleteBlogPost(
    args: Prisma.BlogPostDeleteArgs
  ): Promise<PrismaBlogPost> {
    return this.prisma.blogPost.delete(args);
  }

  async findComments(
    parentId: string,
    args: Prisma.CommentFindManyArgs
  ): Promise<PrismaComment[]> {
    return this.prisma.blogPost
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .comments(args);
  }

  async getAuthor(parentId: string): Promise<PrismaAuthor | null> {
    return this.prisma.blogPost
      .findUnique({
        where: { id: parentId },
      })
      .author();
  }
  async PublishBlogPost(args: PublishBlogPostInput): Promise<string> {
    throw new Error("Not implemented");
  }
}
